In [13]:
import pandas as pd


In [14]:
data= pd.read_csv('/kaggle/input/feat-ing-data/cleaned_encoded_data.csv')
data.head()

Age  Attrition  BusinessTravel  DailyRate  Department  DistanceFromHome  \
0   41          1               2       1102           2                 1   
1   49          0               1        279           1                 8   
2   37          1               2       1373           1                 2   
3   33          0               1       1392           1                 3   
4   27          0               2        591           1                 2   

   Education  EducationField  EmployeeCount  EmployeeNumber  ...  \
0          2               1              1               1  ...   
1          1               1              1               2  ...   
2          2               4              1               4  ...   
3          4               1              1               5  ...   
4          1               3              1               7  ...   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                         1             80                 0   
1                         4             80                 1   
2                         2             80                 0   
3                         3             80                 0   
4                         4             80                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6   
1                 10                      3                3              10   
2                  7                      3                3               0   
3                  8                      3                3               8   
4                  6                      3                3               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 35 columns]

In [15]:
y= data['Attrition']
X=data.drop(columns=['Attrition'])

In [16]:
X

Age  BusinessTravel  DailyRate  Department  DistanceFromHome  Education  \
0      41               2       1102           2                 1          2   
1      49               1        279           1                 8          1   
2      37               2       1373           1                 2          2   
3      33               1       1392           1                 3          4   
4      27               2        591           1                 2          1   
...   ...             ...        ...         ...               ...        ...   
1465   36               1        884           1                23          2   
1466   39               2        613           1                 6          1   
1467   27               2        155           1                 4          3   
1468   49               1       1023           2                 2          3   
1469   34               2        628           1                 8          3   

      EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  \
0                  1              1               1                        2   
1                  1              1               2                        3   
2                  4              1               4                        4   
3                  1              1               5                        4   
4                  3              1               7                        1   
...              ...            ...             ...                      ...   
1465               3              1            2061                        3   
1466               3              1            2062                        4   
1467               1              1            2064                        2   
1468               3              1            2065                        4   
1469               3              1            2068                        2   

      ...  RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0     ...                         1             80                 0   
1     ...                         4             80                 1   
2     ...                         2             80                 0   
3     ...                         3             80                 0   
4     ...                         4             80                 1   
...   ...                       ...            ...               ...   
1465  ...                         3             80                 1   
1466  ...                         1             80                 1   
1467  ...                         2             80                 1   
1468  ...                         4             80                 0   
1469  ...                         1             80                 0   

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                     8                      0                1   
1                    10                      3                3   
2                     7                      3                3   
3                     8                      3                3   
4                     6                      3                3   
...                 ...                    ...              ...   
1465                 17                      3                3   
1466                  9                      5                3   
1467                  6                      0                3   
1468                 17                      3                2   
1469                  6                      3                4   

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                  6                   4                        0   
1                 10                   7                        1   
2                  0                   0                        0   
3                  8                   7                        3   
4                  2                   2                 

# Features_selection

# # # At first we have to normalize the data

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler= StandardScaler()


In [19]:
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(threshold=2)
selector.fit_transform(X)

array([[  41, 1102,    1, ...,    4,    0,    5],
       [  49,  279,    8, ...,    7,    1,    7],
       [  37, 1373,    2, ...,    0,    0,    0],
       ...,
       [  27,  155,    4, ...,    2,    0,    3],
       [  49, 1023,    2, ...,    6,    0,    8],
       [  34,  628,    8, ...,    3,    1,    2]])

In [20]:
selector.get_support()

array([ True, False,  True, False,  True, False, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
        True,  True, False, False,  True, False, False, False, False,
        True, False, False,  True,  True,  True,  True])

In [21]:
selector.get_feature_names_out()

array(['Age', 'DailyRate', 'DistanceFromHome', 'EmployeeNumber',
       'HourlyRate', 'JobRole', 'MonthlyIncome', 'MonthlyRate',
       'NumCompaniesWorked', 'PercentSalaryHike', 'TotalWorkingYears',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'], dtype=object)

# # # # These are features with siginificant variables.

In [22]:
X_selected = data[['Age', 'DailyRate', 'DistanceFromHome', 'EmployeeNumber', 'HourlyRate', 'JobRole', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'TotalWorkingYears', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']]
X_selected

Age  DailyRate  DistanceFromHome  EmployeeNumber  HourlyRate  JobRole  \
0      41       1102                 1               1          94        7   
1      49        279                 8               2          61        6   
2      37       1373                 2               4          92        2   
3      33       1392                 3               5          56        6   
4      27        591                 2               7          40        2   
...   ...        ...               ...             ...         ...      ...   
1465   36        884                23            2061          41        2   
1466   39        613                 6            2062          42        0   
1467   27        155                 4            2064          87        4   
1468   49       1023                 2            2065          63        7   
1469   34        628                 8            2068          82        2   

      MonthlyIncome  MonthlyRate  NumCompaniesWorked  PercentSalaryHike  \
0              5993        19479                   8                 11   
1              5130        24907                   1                 23   
2              2090         2396                   6                 15   
3              2909        23159                   1                 11   
4              3468        16632                   9                 12   
...             ...          ...                 ...                ...   
1465           2571        12290                   4                 17   
1466           9991        21457                   4                 15   
1467           6142         5174                   1                 20   
1468           5390        13243                   2                 14   
1469           4404        10228                   2                 12   

      TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                     8               6                   4   
1                    10              10                   7   
2                     7               0                   0   
3                     8               8                   7   
4                     6               2                   2   
...                 ...             ...                 ...   
1465                 17               5                   2   
1466                  9               7                   7   
1467                  6               6                   2   
1468                 17               9                   6   
1469                  6               4                   3   

      YearsSinceLastPromotion  YearsWithCurrManager  
0                           0                     5  
1                           1                     7  
2                           0                     0  
3                           3                     0  
4                           2                     2  
...                       ...                   ...  
1465                        0                     3  
1466                        1                     7  
1467                        0                     3  
1468                        0                     8  
1469                        1                     2  

[1470 rows x 15 columns]

# # Use PCA to select features

In [23]:
X_scaled= scaler.fit_transform(X_selected)
X_scaled

array([[ 0.4463504 ,  0.74252653, -1.01090934, ..., -0.0632959 ,
        -0.67914568,  0.24583399],
       [ 1.32236521, -1.2977746 , -0.14714972, ...,  0.76499762,
        -0.36871529,  0.80654148],
       [ 0.008343  ,  1.41436324, -0.88751511, ..., -1.16768726,
        -0.67914568, -1.15593471],
       ...,
       [-1.08667552, -1.60518328, -0.64072665, ..., -0.61549158,
        -0.67914568, -0.31487349],
       [ 1.32236521,  0.54667746, -0.88751511, ...,  0.48889978,
        -0.67914568,  1.08689522],
       [-0.32016256, -0.43256792, -0.14714972, ..., -0.33939374,
        -0.36871529, -0.59522723]])

In [24]:
import numpy as np
from sklearn.decomposition import PCA

In [25]:
## Apply PCA
pca = PCA(n_components=0.999)
X_pca = pca.fit_transform(X_scaled)

# print ratio_
print(f'Variance expliquée par chaque composant principal: {pca.explained_variance_ratio_}')
print(f'Variance expliquée cumulative: {pca.explained_variance_ratio_.cumsum()}')


Variance expliquée par chaque composant principal: [0.26875064 0.11100708 0.07248376 0.07067816 0.06878807 0.06519033
 0.06365362 0.0617041  0.06164173 0.04836967 0.03538439 0.0313277
 0.01885967 0.01281877 0.00934231]
Variance expliquée cumulative: [0.26875064 0.37975773 0.45224149 0.52291965 0.59170771 0.65689804
 0.72055167 0.78225577 0.8438975  0.89226717 0.92765156 0.95897926
 0.97783892 0.99065769 1.        ]


In [26]:
pca.get_feature_names_out()

array(['pca0', 'pca1', 'pca2', 'pca3', 'pca4', 'pca5', 'pca6', 'pca7',
       'pca8', 'pca9', 'pca10', 'pca11', 'pca12', 'pca13', 'pca14'],
      dtype=object)

## Models training

I decided to train these 06 classifier models and I'll choose the best according to their accuracy and precision:

 SGDClassifier(),
 LinearSVC(),
 SVC(),
 KNeighborsClassifier(),
 AdaBoostClassifier(),
 RandomForestClassifier()

In [27]:
X_scaled= scaler.fit_transform(X_selected)
X_scaled

array([[ 0.4463504 ,  0.74252653, -1.01090934, ..., -0.0632959 ,
        -0.67914568,  0.24583399],
       [ 1.32236521, -1.2977746 , -0.14714972, ...,  0.76499762,
        -0.36871529,  0.80654148],
       [ 0.008343  ,  1.41436324, -0.88751511, ..., -1.16768726,
        -0.67914568, -1.15593471],
       ...,
       [-1.08667552, -1.60518328, -0.64072665, ..., -0.61549158,
        -0.67914568, -0.31487349],
       [ 1.32236521,  0.54667746, -0.88751511, ...,  0.48889978,
        -0.67914568,  1.08689522],
       [-0.32016256, -0.43256792, -0.14714972, ..., -0.33939374,
        -0.36871529, -0.59522723]])

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score,GridSearchCV

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC, SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

# Initialiser les modèles

X_train,X_test, y_train,y_test= train_test_split(X_scaled,y, test_size=0.3, random_state=42)
models = {
    'SGDClassifier': SGDClassifier(),
    'LinearSVC': LinearSVC(),
    'SVC': SVC(),
    'KNeighborsClassifier': KNeighborsClassifier(),
    'AdaBoostClassifier': AdaBoostClassifier(),
    'RandomForestClassifier': RandomForestClassifier()
}

# Entraîner et évaluer les modèles
results = {}
for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train, cv=50)
    results[name] = scores
    print(f'{name} - Scores: {scores}')
    print(f'{name} - Mean Accuracy: {scores.mean()}')
    print("===============================================================================")
    
print("\n\n")   
    
# Afficher les résultats
for name, scores in results.items():
    print(f'{name} - Mean Accuracy: {scores.mean():.2f} - Std Deviation: {scores.std():.2f}')
    print("==================================================================================")


SGDClassifier - Scores: [0.9047619  0.80952381 0.85714286 0.76190476 0.71428571 0.95238095
 0.76190476 0.9047619  0.61904762 0.80952381 0.85714286 0.76190476
 0.76190476 0.80952381 0.85714286 0.85714286 0.71428571 0.76190476
 0.71428571 0.80952381 0.71428571 0.85714286 0.71428571 0.76190476
 0.76190476 0.80952381 0.71428571 0.76190476 0.80952381 0.85
 0.9        0.85       0.75       0.85       0.8        0.8
 0.8        0.85       0.85       0.75       0.9        0.75
 0.75       0.85       0.95       0.9        0.75       0.75
 0.75       0.8       ]
SGDClassifier - Mean Accuracy: 0.802095238095238


/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  w

LinearSVC - Scores: [0.85714286 0.85714286 0.85714286 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.85
 0.85       0.85       0.85       0.85       0.85       0.85
 0.85       0.85       0.85       0.85       0.9        0.85
 0.85       0.85       0.85       0.85       0.85       0.85
 0.85       0.85      ]
LinearSVC - Mean Accuracy: 0.8303809523809523
SVC - Scores: [0.85714286 0.85714286 0.85714286 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.76190476
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381
 0.80952381 0.80952381 0.80952381 0.80952381 0.80952381 0.85
 0.85       0.85       0.85       0.85       0.85      

## Le tuning des parametres 

In [30]:
import warnings
warnings.filterwarnings("ignore")
# Grille of hyperparameters
param_grids = {
    'SGDClassifier': {
        'loss': ['hinge', 'log_loss', 'modified_huber'],
        'penalty': ['l2', 'l1', 'elasticnet'],
        'alpha': [0.0001, 0.001, 0.01, 0.1]
#     },
#     'LinearSVC': {
#         'C': [0.01, 0.1, 1, 10, 100],
#         'loss': ['hinge', 'squared_hinge']
  },
#     'SVC': {
#         'C': [0.01, 0.1, 1, 10, 100],
#         'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
#         'gamma': ['scale', 'auto']
#     },
    'KNeighborsClassifier': {
        'n_neighbors': [3, 5, 7, 9],
        'weights': ['uniform', 'distance'],
        'metric': ['euclidean', 'manhattan']
    },
    'AdaBoostClassifier': {
        'n_estimators': [50, 100, 200],
        'learning_rate': [0.001, 0.01, 0.1, 1]
    },
    'RandomForestClassifier': {
        'n_estimators': [50, 100, 200],
        'max_features': [None, 'sqrt', 'log2'],
        'max_depth': [None, 10, 20, 30]
    }
}

# Initialize models
models = {
    'SGDClassifier': SGDClassifier(),
#     'LinearSVC': LinearSVC(),
#     'SVC': SVC(),
    'KNeighborsClassifier': KNeighborsClassifier(),
    'AdaBoostClassifier': AdaBoostClassifier(),
    'RandomForestClassifier': RandomForestClassifier()
}

# Function for grid
def tune_model(model, param_grid, X, y):
    grid_search = GridSearchCV(model, param_grid, cv=50, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X, y)
    return grid_search.best_estimator_, grid_search.best_params_, grid_search.best_score_

# Entraîner et tuner les modèles
best_estimators = {}
for name, model in models.items():
    print(f'Tuning {name}...')
    best_estimator, best_params, best_score = tune_model(model, param_grids[name], X_train, y_train)
    best_estimators[name] = best_estimator
    print(f'Best params for {name}: {best_params}')
    print(f'Best score for {name}: {best_score}')

# Résumé des meilleurs modèles
for name, estimator in best_estimators.items():
    print(f'Best estimator for {name}: {estimator}')

Tuning SGDClassifier...
Best params for SGDClassifier: {'alpha': 0.01, 'loss': 'modified_huber', 'penalty': 'l2'}
Best score for SGDClassifier: 0.8331904761904763
Tuning KNeighborsClassifier...
Best params for KNeighborsClassifier: {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'uniform'}
Best score for KNeighborsClassifier: 0.8323809523809524
Tuning AdaBoostClassifier...
Best params for AdaBoostClassifier: {'learning_rate': 0.1, 'n_estimators': 100}
Best score for AdaBoostClassifier: 0.838095238095238
Tuning RandomForestClassifier...
Best params for RandomForestClassifier: {'max_depth': 30, 'max_features': 'log2', 'n_estimators': 200}
Best score for RandomForestClassifier: 0.8401904761904762
Best estimator for SGDClassifier: SGDClassifier(alpha=0.01, loss='modified_huber')
Best estimator for KNeighborsClassifier: KNeighborsClassifier(metric='manhattan', n_neighbors=9)
Best estimator for AdaBoostClassifier: AdaBoostClassifier(learning_rate=0.1, n_estimators=100)
Best estimator fo

# Best model with best parameters

Model: RandomForestClassifier 
Params: max_depth:30; max_features: 'sqrt'; n_estimators:10

with a score: 0.84

In [33]:
### best model 
best_model = RandomForestClassifier(max_depth=30, random_state=42, max_features='log2', n_estimators=200)
best_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=30, max_features='log2', n_estimators=200,
                       random_state=42)

In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# make prediction with X_test
y_pred = best_model.predict(X_test)

# Calulate precision
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")


# display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.85
Confusion Matrix:
 [[368  12]
 [ 56   5]]


# Save the best model

In [35]:
import joblib
joblib.dump(best_model, 'best_model.pkl')

['best_model.pkl']